modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="simplerecall"
version="1.0.0"
displayName="Simple Recall Potion"
authors="gobies"
description='''simple recall potion inspired by terraria!'''

[[dependencies.simplerecall]]
modId="forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplerecall]]
modId="minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"

