modLoader="javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId="simplerecall"
version="1.0.5"
displayName="Simple Recall Potion"
authors="gobies"
description='''simple recall potion inspired by terraria!'''

[[dependencies.simplerecall]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplerecall]]
modId="minecraft"
mandatory= true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

